version: "3.9"

services:
  pg_node1:
    image: postgres:16
    container_name: pg_node1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: labdb
    ports:
      - "5433:5432"
    volumes:
      - pg_node1_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  pg_node2:
    image: postgres:16
    container_name: pg_node2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: labdb
    ports:
      - "5434:5432"
    volumes:
      - pg_node2_data:/var/lib/postgresql/data

  pg_node3:
    image: postgres:16
    container_name: pg_node3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: labdb
    ports:
      - "5435:5432"
    volumes:
      - pg_node3_data:/var/lib/postgresql/data

volumes:
  pg_node1_data:
  pg_node2_data:
  pg_node3_data:
