services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd
    environment:
      ETCD_NAME: etcd
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_INITIAL_CLUSTER: etcd=http://etcd:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster
    ports:
      - "2379:2379"
    networks:
      - patroni_net

  patroni1:
    image: ghcr.io/zalando/spilo-16:3.2-p3
    container_name: patroni1
    hostname: patroni1
    environment:
      SCOPE: postgres-cluster
      ETCD3_HOSTS: etcd:2379
      PATRONI_REPLICATION_USERNAME: repl_user
      PATRONI_REPLICATION_PASSWORD: repl_pass
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_SUPERUSER_PASSWORD: postgres
      PATRONI_RESTAPI_USERNAME: admin
      PATRONI_RESTAPI_PASSWORD: admin
    volumes:
      - patroni1_data:/home/postgres/pgdata
    ports:
      - "5433:5432"
      - "8008:8008"
    networks:
      - patroni_net
    depends_on:
      - etcd

  patroni2:
    image: ghcr.io/zalando/spilo-16:3.2-p3
    container_name: patroni2
    hostname: patroni2
    environment:
      SCOPE: postgres-cluster
      ETCD3_HOSTS: etcd:2379
      PATRONI_REPLICATION_USERNAME: repl_user
      PATRONI_REPLICATION_PASSWORD: repl_pass
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_SUPERUSER_PASSWORD: postgres
      PATRONI_RESTAPI_USERNAME: admin
      PATRONI_RESTAPI_PASSWORD: admin
    volumes:
      - patroni2_data:/home/postgres/pgdata
    ports:
      - "5434:5432"
      - "8009:8008"
    networks:
      - patroni_net
    depends_on:
      - etcd

  patroni3:
    image: ghcr.io/zalando/spilo-16:3.2-p3
    container_name: patroni3
    hostname: patroni3
    environment:
      SCOPE: postgres-cluster
      ETCD3_HOSTS: etcd:2379
      PATRONI_REPLICATION_USERNAME: repl_user
      PATRONI_REPLICATION_PASSWORD: repl_pass
      PATRONI_SUPERUSER_USERNAME: postgres
      PATRONI_SUPERUSER_PASSWORD: postgres
      PATRONI_RESTAPI_USERNAME: admin
      PATRONI_RESTAPI_PASSWORD: admin
    volumes:
      - patroni3_data:/home/postgres/pgdata
    ports:
      - "5435:5432"
      - "8010:8008"
    networks:
      - patroni_net
    depends_on:
      - etcd

networks:
  patroni_net:
    driver: bridge

volumes:
  patroni1_data:
  patroni2_data:
  patroni3_data:
